
language: csharp

sudo: required
dist: trusty

before_install:
  - sudo sh -c 'echo "deb [arch=amd64] https://apt-mo.trafficmanager.net/repos/dotnet-release/ trusty main" > /etc/apt/sources.list.d/dotnetdev.list'
  - sudo apt-key adv --keyserver apt-mo.trafficmanager.net --recv-keys 417A0893
  - sudo apt-get update
  - sudo apt-get install dotnet-dev-1.0.0-preview2-003131

script:
  - mono .nuget/NuGet.exe restore packages.config -PackagesDirectory packages -ConfigFile .nuget/NuGet.Config
  - (cd lkg;  dotnet restore --packages ../packages && dotnet publish project.json -o ../tools/lkg -r ubuntu.14.04-x64)
  - xbuild src/fsharp-proto-build.proj
  - cp src/fsharp/FSharp.Build/Microsoft.FSharp.targets tools
  - cp src/fsharp/FSharp.Build/Microsoft.Portable.FSharp.targets tools
  - xbuild build-everything.proj /p:Configuration=debug /p:BUILD_PUBLICSIGN=0
  - mono .nuget/NuGet.exe restore  ./tests/fsharp/project.json -PackagesDirectory packages -ConfigFile .nuget/NuGet.Config


  



