os: Windows Server 2012 R2

init:
  - git config --global core.autocrlf input

# scripts that run after cloning repository
install:
  # by default, all script lines are interpreted as batch
  - set PATH=%ProgramFiles(x86)%\MSBuild\14.0\Bin;%PATH%

build_script:
  - ps: .\install-dnx.ps1
  - cmd: dnu restore --packages packages
  - cmd: appveyor-build.cmd

test: off
version: '{build}'
artifacts:
  - path: Release
    name: Release
