os: Visual Studio 2015

init:
  - git config --global core.autocrlf input

# scripts that run after cloning repository
install:
  # by default, all script lines are interpreted as batch
  - set PATH=%ProgramFiles(x86)%\MSBuild\14.0\Bin;%PATH%

build_script:
  - ps: |
      .\install-dnx.ps1
      # https://github.com/aspnet/dnx/issues/3004
      cp .\.nuget\NuGet.Config $env:appdata\NuGet\NuGet.config
  - cmd: appveyor-build.cmd

test: off
version: '{build}'
artifacts:
  - path: Release
    name: Release
