os: Visual Studio 2015

environment:
  matrix:
    - BUILD_PROFILE: net40
    - BUILD_PROFILE: portable7
    - BUILD_PROFILE: portable47
    - BUILD_PROFILE: portable78
    - BUILD_PROFILE: portable259
    - BUILD_PROFILE: vs
    - BUILD_PROFILE: cambridge_suite
    - BUILD_PROFILE: qa_suite

init: 
build_script: 
  - cmd: appveyor-build.cmd %BUILD_PROFILE%

# scripts that run after cloning repository
install:
  # by default, all script lines are interpreted as batch
  - set PATH=%ProgramFiles(x86)%\MSBuild\14.0\Bin;%PATH%

test: off 
version: 0.0.1.{build} 
artifacts: 
  - path: Release
    name: Release
