os: Windows Server 2012 R2

init:
  - git config --global core.autocrlf input

# scripts that run after cloning repository
install:
  # by default, all script lines are interpreted as batch
  - set PATH=%ProgramFiles(x86)%\MSBuild\14.0\Bin;%PATH%

build_script: 
  - ps: |
      $x64items = @(Get-ChildItem "HKLM:SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall")
      $x64items + @(Get-ChildItem "HKLM:SOFTWARE\wow6432node\Microsoft\Windows\CurrentVersion\Uninstall") `
         | ForEach-object { Get-ItemProperty Microsoft.PowerShell.Core\Registry::$_ } `
         | Sort-Object -Property DisplayName `
         | Select-Object -Property DisplayName,DisplayVersion
      #ls env: | Write-Output
      #.\install-dnx.ps1
      # https://github.com/aspnet/dnx/issues/3004
      #cp .\.nuget\NuGet.Config $env:appdata\NuGet\NuGet.config
      #dnu restore --packages packages
  #- cmd: appveyor-build.cmd

test: off
version: '{build}'
artifacts: 
  - path: Release
    name: Release